//! # D-Bus interface proxy for: `service.rebpf`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/' from service 'service.rebpf' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use std::collections::HashMap;

use zbus::proxy;
#[proxy(
    interface = "service.rebpf",
    default_service = "service.rebpf",
    default_path = "/"
)]
pub trait Ser {
    fn change_output(&self, arg_1: &str) -> zbus::Result<()>;

    fn update_config(&self, arg_1: &std::collections::HashMap<&str, String>) -> zbus::Result<()>;

    /// AddMatch method
    fn add_match(&self, arg_1: &std::collections::HashMap<&str, String>) -> zbus::Result<()>;

    /// DeleteMatch method
    fn delete_match(&self, arg_1: &std::collections::HashMap<&str, String>) -> zbus::Result<()>;

    /// Disable method
    fn disable(&self) -> zbus::Result<()>;

    /// Enable method
    fn enable(&self) -> zbus::Result<()>;

    /// ForceReload method
    fn force_reload(&self) -> zbus::Result<()>;

    fn get_stats(&self) -> zbus::Result<HashMap<String, String>>;

    /// GetProcNames method
    fn get_proc_names(&self) -> zbus::Result<String>;

    /// Toggle method
    fn toggle(&self) -> zbus::Result<()>;

    /// UpdateMatch method
    fn update_match(
        &self,
        arg_1: &std::collections::HashMap<&str, String>,
        arg_2: &std::collections::HashMap<&str, String>,
    ) -> zbus::Result<()>;

    /// Attached property
    #[zbus(property)]
    fn attached(&self) -> zbus::Result<std::collections::HashMap<String, String>>;

    /// Matches property
    #[zbus(property)]
    fn matches(&self) -> zbus::Result<Vec<std::collections::HashMap<String, String>>>;

    /// Config property
    #[zbus(property)]
    fn config(&self) -> zbus::Result<std::collections::HashMap<String, String>>;

    /// SocketMark property
    #[zbus(property)]
    fn socket_mark(&self) -> zbus::Result<i32>;
}
